apiVersion: v1
kind: Service
metadata:
  name: smart-alert-api
  namespace: smart-alerting
spec:
  selector:
    app: smart-alert-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
